config/routes.rb
Tracker::Application.routes.draw do
  root :to => "home#index"
  

  resources :users

  resources :tasks do
    get "finish", :on => :member 
  end

  resources :proyects do
    get ":id/test" => "homes#index"
    put "adduser" , :on=> :member
  end
  
  match 'home/index' => 'home#index'
  
  

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many:users
  
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many:users
  
end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
  has_many:tasks
  belongs_to:user
  belongs_to:status
  has_and_belongs_to_many:users
end
#componer asociacion 

app/models/status.rb
class Status < ActiveRecord::Base
  has_many:proyects
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to:proyect
  belongs_to:tasktype
  belongs_to:user
end

app/models/tasktype.rb
class Tasktype < ActiveRecord::Base
  has_many:tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one:proyect
  belongs_to:country
  belongs_to:language
  has_and_belongs_to_many :proyect
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/proyect_user_relation_controller.rb
class ProyectUserRelationController < ApplicationController

end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyects }
    end
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/new
  # GET /proyects/new.json
  def new
    @proyect = Proyect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/1/edit
  def edit
    @proyect = Proyect.find(params[:id])
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(params[:proyect])

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render json: @proyect, status: :created, location: @proyect }
      else
        format.html { render action: "new" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyects/1
  # PUT /proyects/1.json
  def update
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      if @proyect.update_attributes(params[:proyect])
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect = Proyect.find(params[:id])
    @proyect.destroy

    respond_to do |format|
      format.html { redirect_to proyects_url }
      format.json { head :ok }
    end
  end
  def test
    @proyect =Proyect.find(params[:id]).tasks
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def adduser
    @proyect = Proyect.find(params[:id])
    @user = User.find(params[:proyect][:user_id])
    @proyect.users << @user
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    respond_to do |format|
      if @task.save
	
#         format.html { redirect_to @task.proyect, notice: 'Task was successfully created.' }
	format.html
	format.js
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def finish
    @task=Task.find(params[:id])
    respond_to do | format|
      if @task.update_attributes(:end_bit=>1);
	format.html
	format.js
      else
	format.html
	format.json { render json: @task.errors, status: :unprocessable_entity }
      end
	
    end
    
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proyect_user_relation_helper.rb
module ProyectUserRelationHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
.well
  %h1 Principal page
  %p please select from side bar.

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Tracker"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Tracker
          .container.nav-collapse
            %ul.nav
              %li= link_to "Home", "/home/index"
              %li= link_to "Help", "/path2"
              %li= link_to "About", "/path3"

    .container

      .content
        .row
          .span10
            = yield
          .span2
            .well.sidebar-nav
              %h3 Listig Resources
              %ul.nav.nav-list
                %li.nav-header View a list of:
                %li= link_to "Proyects", proyects_path
                %li= link_to "Tasks", tasks_path
                %li= link_to "Users", users_path
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/proyects/_appendUser.html.haml
-usr=@user
%tr
  %td= link_to usr.user_name, user_path(usr)
  %td=usr.name
  %td=usr.email
  %td
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(usr), :class => 'btn btn-mini'
    

app/views/proyects/_form.html.haml
= form_for @proyect, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :begin_date, :class => 'control-label'
    .controls
      = f.datetime_select :begin_date, :class => 'datetime_select'
  .control-group
    = f.label :end_time, :class => 'control-label'
    .controls
      = f.datetime_select :end_time, :class => 'datetime_select'
  .control-group
    = f.label :status_id, :class => 'control-label'
    .controls
      = collection_select(:proyect, :status_id, Status.all, :id, :name)
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = collection_select(:proyect, :user_id, User.all, :id, :user_name)
  .control-group
    = f.label :protect_bit, :class => 'control-label'
    .controls
      = f.number_field :protect_bit, :class => 'number_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), proyects_path, :class => 'btn'

app/views/proyects/adduser.js.haml
alert('User successfully linked!');
$('#newUserModal').modal('hide');
$('#users_table tbody').append("#{escape_javascript(render :partial=>'appendUser')}");

app/views/proyects/create.js.haml
$('body').html("%h1>= escape_javaScript(@proyect.title)").append("#{escape_javaScript(@proyect.description)}");

app/views/proyects/edit.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/proyects/index.html.haml
- model_class = Proyect.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:begin_date)
      %th= model_class.human_attribute_name(:end_time)
      %th= model_class.human_attribute_name(:status_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:protect_bit)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @proyects.each do |proyect|
      %tr
        %td= link_to proyect.id, proyect_path(proyect)
        %td= link_to proyect.title,proyect_path(proyect)
        %td= proyect.description
        %td= proyect.begin_date
        %td= proyect.end_time
        %td= proyect.status.name
        %td= proyect.user.user_name
        %td= proyect.protect_bit
        %td=l proyect.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_proyect_path(proyect), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), proyect_path(proyect), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_proyect_path, :class => 'btn btn-primary'

app/views/proyects/new.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/proyects/show.html.haml
- model_class = @proyect.class
%h1=t '.title', :default => model_class.model_name.human
.well
  %p
    %strong= model_class.human_attribute_name(:title) + ':'
    %br
    = @proyect.title
  %p
    %strong= model_class.human_attribute_name(:description) + ':'
    %br
    = @proyect.description
  %p
    %strong= model_class.human_attribute_name(:begin_date) + ':'
    %br
    = @proyect.begin_date
  %p
    %strong= model_class.human_attribute_name(:end_time) + ':'
    %br
    = @proyect.end_time
  %p
    %strong= model_class.human_attribute_name(:status_id) + ':'
    %br
    = @proyect.status.name
  %p
    %strong= model_class.human_attribute_name(:user_id) + ':'
    %br
    = @proyect.user.user_name
  %p
    %strong= model_class.human_attribute_name(:protect_bit) + ':'
    %br
    = @proyect.protect_bit

  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), proyects_path, :class => 'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_proyect_path(@proyect), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), proyect_path(@proyect), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'
  
%h1 Proyect Components
%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", :href => "#Tasks"} Tasks
  %li
    %a{"data-toggle" => "tab", :href => "#Developers"} Saludo
  %li
    %a{:href => "#"} ...
    
.tab-content
  .tab-pane.active#Tasks
    %table.table.table-striped#tasks_table
      %thead
        %tr
        %th{:colspan=>7}
          %a{"data-toggle" => "modal",:href=>"#newTaskModal",:class=>"btn"}New Task
        %tr
        %th Title
        %th Difficulty
        %th Description
        %th Begin date 
        %th Type
        %th Responsable
        %th Finished
      
      %tbody
        - @proyect.tasks.each do |t|
          %tr
          %td= link_to t.title, task_path(t)
          %td= t.difficulty
          %td= t.description
          %td= t.begin_time
          %td= t.tasktype.name
          %td= link_to t.user.user_name, user_path(t.user)
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(t), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(t), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
            = link_to 'Finish', finish_task_path(t), :class=>'btn btn-success', :remote=>true
    

  .tab-pane#Developers
    %table.table.table-striped#users_table
      %thead
        %tr
        %th{:colspan=>4}
          %a{"data-toggle" => "modal",:href=>"#newUserModal",:class=>"btn"}New User
        %tr
        %th Name
        %th User Name
        %th email
      %tbody
        - @proyect.users.each do |usr|
          %tr
          %td= link_to usr.user_name, user_path(usr)
          %td=usr.name
          %td=usr.email
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(usr), :class => 'btn btn-mini'
            
  
      
        
.modal.hide.fade#newTaskModal
  .modal-header
    %button.close{"data-dismiss"=>"modal"}x
    %h2 Add New Tasks
  .modal-body
    %p 
    - @task=Task.new
    - model_class = @task.class
    = render :partial => "tasks/form"
    
.modal.hide.fade#newUserModal
  .modal-header
    %button.close{"data-dismiss"=>"modal"}x
    %h2 Add New User
  .modal-body
    =form_for @proyect, :url => adduser_proyect_path,:html => { :method=>'put',:class => 'form-horizontal' ,:remote=> true} do |f|
      = f.label :user_id, :class => 'control-label'
      .controls
        = collection_select(:proyect, :user_id, User.all, :id, :user_name)
        = f.text_field :id, :class => 'text_area',:value=>"#{@proyect.id}",:type=>"hidden"
      .form-actions
        = f.submit nil, :class => 'btn btn-primary'

app/views/tasks/_appendTask.html.haml
- t=@task
%tr
  %td= link_to t.title, task_path(t)
  %td= t.difficulty
  %td= t.description
  %td= t.begin_time
  %td= t.tasktype.name
  %td= link_to t.user.user_name, user_path(t.user)
  %td
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(t), :class => 'btn btn-mini'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(t), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
    = link_to 'Finish', finish_task_path(t), :class=>'btn btn-success', :remote=>true

app/views/tasks/_form.html.haml
= form_for @task, :html => { :class => 'form-horizontal' ,:remote=> true } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :difficulty, :class => 'control-label'
    .controls
      = f.number_field :difficulty, :class => 'number_field'
  .control-group
    = f.label :begin_time, :class => 'control-label'
    .controls
      = f.datetime_select :begin_time, :class => 'datetime_select'
  .control-group
    = f.label :end_time, :class => 'control-label'
    .controls
      = f.datetime_select :end_time, :class => 'datetime_select'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = collection_select(:task, :user_id, User.all, :id, :user_name)
  .control-group
    = f.label :proyect_id, :class => 'control-label'
    .controls
      = collection_select(:task, :proyect_id, Proyect.all, :id, :title)
  .control-group
    = f.label :tasktype_id, :class => 'control-label'
    .controls
      = collection_select(:task, :tasktype_id, Tasktype.all, :id, :name)
  .control-group
    = f.label :end_bit, :class => 'control-label'
    .controls
      = select( "task", "end_bit", { "True" => "1", "False" => "0"})
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn'

app/views/tasks/create.js.haml
alert('Task successfully added!');
$('#newTaskModal').modal('hide');
$('#tasks_table tbody').append("#{escape_javascript(render :partial=>'appendTask')}");

app/views/tasks/edit.html.haml
- model_class = @task.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/tasks/finish.js.haml
alert('Task successfully finished!');

app/views/tasks/index.html.haml
- model_class = Task.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:difficulty)
      %th= model_class.human_attribute_name(:begin_time)
      %th= model_class.human_attribute_name(:end_time)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:proyect_id)
      %th= model_class.human_attribute_name(:tasktype_id)
      %th= model_class.human_attribute_name(:end_bit)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= link_to task.title, task_path(task)
        %td= task.description
        %td= task.difficulty
        %td= task.begin_time
        %td= task.end_time
        %td= link_to task.user.user_name, user_path(task.user)
        %td= link_to task.proyect.title, proyect_path(task.proyect)
        %td= task.tasktype.name
        %td= task.end_bit
        %td=l task.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'

app/views/tasks/new.html.haml
- model_class = @task.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/tasks/new.js.haml
alert('Visca el Barca!');

app/views/tasks/show.html.haml
- model_class = @task.class
%h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @task.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @task.description
%p
  %strong= model_class.human_attribute_name(:difficulty) + ':'
  %br
  = @task.difficulty
%p
  %strong= model_class.human_attribute_name(:begin_time) + ':'
  %br
  = @task.begin_time
%p
  %strong= model_class.human_attribute_name(:end_time) + ':'
  %br
  = @task.end_time
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @task.user.user_name
%p
  %strong= model_class.human_attribute_name(:proyect_id) + ':'
  %br
  = @task.proyect.title
%p
  %strong= model_class.human_attribute_name(:tasktype_id) + ':'
  %br
  = @task.tasktype.name
%p
  %strong= model_class.human_attribute_name(:end_bit) + ':'
  %br
  = @task.end_bit

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :biography, :class => 'control-label'
    .controls
      = f.text_area :biography, :class => 'text_area'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :user_name, :class => 'control-label'
    .controls
      = f.text_field :user_name, :class => 'text_field'
  .control-group
    = f.label :country_id, :class => 'control-label'
    .controls
      = collection_select(:user, :country_id, Country.all, :id, :name)
  .control-group
    = f.label :language_id, :class => 'control-label'
    .controls
      = collection_select(:user, :language_id, Language.all, :id, :name)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:biography)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:user_name)
      %th= model_class.human_attribute_name(:country_id)
      %th= model_class.human_attribute_name(:language_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.biography
        %td= user.email
        %td= user.password
        %td= user.user_name
        %td= user.country_id
        %td= user.language_id
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
	
= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = @user.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.haml
- model_class = @user.class
%h1=t '.title', :default => model_class.model_name.human
.well
  %p
    %strong= model_class.human_attribute_name(:name) + ':'
    %br
    = @user.name
  %p
    %strong= model_class.human_attribute_name(:biography) + ':'
    %br
    = @user.biography
  %p
    %strong= model_class.human_attribute_name(:email) + ':'
    %br
    = @user.email
  %p
    %strong= model_class.human_attribute_name(:password) + ':'
    %br
    = @user.password
  %p
    %strong= model_class.human_attribute_name(:user_name) + ':'
    %br
    = @user.user_name
  %p
    %strong= model_class.human_attribute_name(:country_id) + ':'
    %br
    = @user.country.name
  %p
    %strong= model_class.human_attribute_name(:language_id) + ':'
    %br
    = @user.language.name

  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'